apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy2
  name: deploy2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy2
    spec:
      containers:
      - image: gcr.io/genuine-fold-316617/sam:v1.0
        name: sam
        resources: {}
status: {}
